
package com.bancoabc.pagorest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-25T14:45:52.883+05:30
 * Generated source version: 2.7.0
 */

@WebFault(name = "getQuoteFault", targetNamespace = "http://pagos.servicios.com/quote/")
public class GetPagoOperationFault extends Exception {
    
    private com.bancoabc.pagorest.GetPagoFault getPagoFault;

    public GetPagoOperationFault() {
        super();
    }
    
    public GetPagoOperationFault(String message) {
        super(message);
    }
    
    public GetPagoOperationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPagoOperationFault(String message, com.bancoabc.pagorest.GetPagoFault getPagoFault) {
        super(message);
        this.getPagoFault = getPagoFault;
    }

    public GetPagoOperationFault(String message, com.bancoabc.pagorest.GetPagoFault getPagoFault, Throwable cause) {
        super(message, cause);
        this.getPagoFault = getPagoFault;
    }

    public com.bancoabc.pagorest.GetPagoFault getFaultInfo() {
        return this.getPagoFault;
    }
}
