package com.bancoabc.pagorest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-25T14:45:52.961+05:30
 * Generated source version: 2.7.0
 * 
 */
public class PagosRestService{
    
}
