package com.bancoabc.pagosoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-25T14:45:53.196+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://pagos.servicios.com/quote/", name = "AirLineAQuote")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiciosSoapPago {

    @WebResult(name = "getQuoteResponse", targetNamespace = "http://pagos.servicios.com/quote/", partName = "parameters")
    @WebMethod(action = "http://pagos.servicios.com/quote/getQuoteOperation")
    public GetPagoResponse getQuoteOperation(
        @WebParam(partName = "parameters", name = "getQuote", targetNamespace = "http://pagos.servicios.com/quote/")
        GetPago parameters
    ) throws GetPagoOperationFault;
}
